$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  sequences:
    type: string
  metadata:
    type: string
  inputs:
    type:
      - array
    minItems: 1
    items:
      type: object
      required:
        - name
        - metadata
      properties:
        name:
          type: string
          minLength: 1
        metadata:
          type: string
          minLength: 1
        sequences:
          type: string
          minLength: 1
        aligned:
          type: string
          minLength: 1
        to-exclude:
          type: string
          minLength: 1
        masked:
          type: string
          minLength: 1
        filtered:
          type: string
          minLength: 1
      additionalProperties: false
