name: Sync RTD redirects

on:
  push:
    branches:
      - master
    paths:
      - docs/redirects.yaml
      - .github/workflows/sync-redirects.yaml

  # Manually triggered using GitHub's UI
  workflow_dispatch:

jobs:
  sync:
    name: rtd redirects
    uses: nextstrain/.github/.github/workflows/sync-rtd-redirects.yaml@master
    with:
      project: nextstrain-ncov
      file: docs/redirects.yaml
    secrets:
      RTD_TOKEN: ${{ secrets.RTD_TOKEN }}
